language: ruby
rvm:
- 2.6.3
env:
- TRAVIS_NODE_VERSION="8.16.0"
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
  && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
  install $TRAVIS_NODE_VERSION
- npm install
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
- bundle install
before_script:
- rails webpacker:install
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
script:
- bundle exec rails test
deploy:
  provider: heroku
  api_key:
    secure: LDK7tBZJ0NOEcFn7VNuCb0U/CjMctrWF2fcr6+hWqBeJxEYUL1XneMfJiC/SXwYxd2/KQpm5hWpRfJR7D6w+JqqM3wrAYvnM3gNG2paclDvUd9tOycoXbDoSjFYc3myofcuf9ivVdwOGgOrkvMhhrHZlP2as0U3GBYCLyIX6Wn7HuLopb8OaXSfvop0BTnJbzvMczxeuBq2d3EuvSkgHEZLblA5PUk29mC/u1CvxYnNx+bSPutmdNFJczQQ0bLszzEwZoZS+BWpsjbXzMPTTvE+hAUudkP0AfdYeuCXNDAkoTZxOsvzXj8vwKJvWkilDGTq5pqGnCWHS/xz9p98Qt1tQJelp4HIHRF1mfzrVOKWu9DHqtVwphm9CBmfyAdNgEHgC7Tzy1i9bum9nk9xNX8UE8cGlsPII1QxeAbjv9y03vUz6NRkWAje5is2J4NdNhtHo+eWmNUGrqvF5WwFaPNYpukRGIGf4NrKDATcJNsVQRzaMZTmuVFvZPRGMtn0xzBo8cu59s6bLC+rsslX4P6lUJ+T75CqcL4CajioucIVYaWNUpKDdJjN/oNlGGO3XQu44+me+0h8pVq0xYSfSNuFIr5jFAedKWqUT2Sfieh1x8sNtLmf/+jmduYbOVsJs8zBXOCh9yzpZvzKrz7fuW4a24sQDkIEnjCxX3MinwPM=
  app: elsys-ci-demo
  run:
  - rake db:create
  - rake db:migrate
